# NumPy 


- Biblioteca de Algera Linear, a maioria das bibliotecas do Ecosistema PyData dependem de Numpy para rodarem.
- Construído em C, ou seja, roda mais rápido.

## Instalação

Anaconda:
conda install numpy

Pip:
pip install numpy

## Usando Numpy

In [1]:
import numpy as np

# Matrizes e arrays

## Numpy Arrays

Arrays são vetores 1D, e matrizes são vetores 2D

## Criando NumPy Arrays de uma lista

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Gera Arrays de 0s e 1s

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna elementos em um intervalo especificado

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Matriz identidade

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

### rand
Cria arrays gerados aleatoriamente no intervalo entre ``[0, 1)``.

In [15]:
np.random.rand(2)

array([ 0.78506237,  0.09725612])

In [16]:
np.random.rand(5,5)

array([[ 0.91167905,  0.58562521,  0.02544176,  0.53244016,  0.90472259],
       [ 0.39124022,  0.37043794,  0.58117911,  0.59883227,  0.72730648],
       [ 0.10180171,  0.39376656,  0.57328785,  0.37754171,  0.53154755],
       [ 0.50560349,  0.58480346,  0.99134237,  0.52360025,  0.1301559 ],
       [ 0.59705469,  0.85380089,  0.82758931,  0.72900841,  0.69532137]])

### randn

Retorna arrays distribuidos aleatoriamente por Standard Normalization

In [17]:
np.random.randn(2)

array([ 0.64639308, -1.45427387])

In [18]:
np.random.randn(5,5)

array([[ 0.34698328,  0.78106138, -1.04974419,  1.90792092,  0.92175543],
       [ 0.3922356 ,  0.60353687, -0.58772135,  0.51680318,  3.11680779],
       [-0.62842612,  0.62732849, -0.49677383,  1.69239295,  0.02659874],
       [ 0.51837436, -0.10383983, -0.35396764,  1.29063926,  0.35813417],
       [-1.14701863,  0.12163129, -0.02194893,  0.13508484, -0.24905428]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).
Retorna inteiros aleatorios entre o intervalo especificado

In [19]:
np.random.randint(1,100)

14

In [20]:
np.random.randint(1,100,10)

array([61, 50, 19, 10, 24, 99,  4, 11, 82, 28])

## Atributos e Métodos de arrays

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([24, 40, 37, 20, 30, 12, 30,  9, 10, 41])

## Reshape
Retorna um array rearranjado

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin


In [25]:
ranarr

array([24, 40, 37, 20, 30, 12, 30,  9, 10, 41])

In [26]:
ranarr.max()

41

In [27]:
ranarr.argmax()

9

In [28]:
ranarr.min()

9

In [29]:
ranarr.argmin()

7

## Shape

Atributo para retornar a dimensão do array

In [30]:
# Vector
arr.shape

(25,)

In [31]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Checando o tipo do objeto

In [35]:
arr.dtype

dtype('int64')

# Great Job!